const section ='Auth'
export const  AuthError   =  {
  "USER_NOT_FOUND" :{ section , info : 'USER_NOT_FOUND' ,msg : '', code : 1000 } ,
  "EMAIL_FIELD_AUTH_IS_REQUIRED" :{ section , info : 'EMAIL_FIELD_AUTH_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "PASSWORD_FIELD_AUTH_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_BANK_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "PATTERN_USER_ID_IS_WRONG" :{ section , info : 'PATTERN_USER_ID_IS_WRONG' , msg : '', code : 1005 } ,
  "ROLE_USER_NOT_FOUND" :{ section , info : 'ROLE_USER_NOT_FOUND' ,msg : '', code : 1000 } ,
  "WALLET_ADDRESS_IS_DUPLICATED" :{ section , info : 'WALLET_ADDRESS_IS_DUPLICATED' , msg : '' , code : 1008 } ,
  "PAYLOAD_FIELD_AUTH_IS_REQUIRED" :{ section , info : 'PAYLOAD_FIELD_AUTH_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "PIN_CODE_FIELD_AUTH_IS_REQUIRED" :{ section , info : 'PIN_CODE_FIELD_AUTH_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "PIN_CODE_FIELD_IS_EMPTY" :{ section , info : 'PIN_CODE_FIELD_IS_EMPTY' , msg : '' , code : 1001 } ,
  "PATTERN_COUNTRY_ID_IS_WRONG" :{ section , info : 'PATTERN_COUNTRY_ID_IS_WRONG' , msg : '', code : 1005 } ,
  "PATTERN_PROVINCE_ID_IS_WRONG" :{ section , info : 'PATTERN_PROVINCE_ID_IS_WRONG' , msg : '', code : 1005 } ,
  "PATTERN_CITY_ID_IS_WRONG" :{ section , info : 'PATTERN_CITY_ID_IS_WRONG' , msg : '', code : 1005 } ,
  "FIRST_NAME_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'FIRST_NAME_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "FIRST_NAME_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'FIRST_NAME_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "LAST_NAME_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'LAST_NAME_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "LAST_NAME_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'LAST_NAME_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "PHOTO_KYC_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'PHOTO_KYC_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "PHOTO_KYC_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'PHOTO_KYC_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "GENDER_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'GENDER_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "GENDER_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'GENDER_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "BIRTH_DATE_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'BIRTH_DATE_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "TYPE_KYC_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'TYPE_KYC_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "TYPE_KYC_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'TYPE_KYC_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "PROVIDER_NOT_FOUND" :{ section , info : 'PROVIDER_NOT_FOUND' ,msg : '', code : 1000 } ,
  "PASSWORD_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'PASSWORD_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "PASSWORD_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'PASSWORD_FIELD_USER_PROFILE_EMPTY' , msg : '' , code : 1002 } ,
  "CONFIRM_PASSWORD_FIELD_USER_PROFILE_REQUIRED" :{ section , info : 'CONFIRM_PASSWORD_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 } ,
  "CONFIRM_PASSWORD_FIELD_USER_PROFILE_EMPTY" :{ section , info : 'CONFIRM_PASSWORD_FIELD_USER_PROFILE_REQUIRED' , msg : '' , code : 1002 }
}

