const section ='Email'
export const  EmailError   =  {
  "TOKEN_NOT_FOUND" :{ section , info : 'TOKEN_NOT_FOUND' , msg : '' , code : 1001 } ,
  "EMAIL_FIELD_EMAIL_IS_REQUIRED" :{ section , info : 'EMAIL_FIELD_EMAIL_IS_REQUIRED' , msg : '' , code : 1003 } ,
  "EMAIL_ALREADY_VERIFYED" :{ section , info : 'EMAIL_ALREADY_VERIFYED' , msg : '' , code : 1003 } ,
  "EMAIL_NOT_FOUND" :{ section , info : 'EMAIL_NOT_FOUND' , msg : '' , code : 1001 } ,
  "EMAIL_ALREADY_REGISTERED" :{ section , info : 'EMAIL_ALREADY_REGISTERED' , msg : '' , code : 1003 } ,
  "TOKEN_FIELD_EMAIL_IS_REQUIRED" :{ section , info : 'TOKEN_FIELD_EMAIL_IS_REQUIRED' , msg : '' , code : 1003 } ,
  "TOKEN_FIELD_EMAIL_IS_EMPTY" :{ section , info : 'TOKEN_FIELD_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "OTP_NOT_FOUND" :{ section , info : 'OTP_NOT_FOUND' , msg : '' , code : 1001 } ,
  "REFRESH_TOKEN_FIELD_EMAIL_IS_REQUIRED" :{ section , info : 'REFRESH_TOKEN_FIELD_EMAIL_IS_REQUIRED' , msg : '' , code : 1003 } ,
  "REFRESH_TOKEN_FIELD_EMAIL_IS_EMPTY" :{ section , info : 'REFRESH_TOKEN_FIELD_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "EMAIL_FROM_EMAIL_IS_DUPLICATED" :{ section , info : 'EMAIL_FROM_EMAIL_IS_DUPLICATED' , msg : '' , code : 1009 } ,
  "OTP_CODE_FIELD_EMAIL_IS_REQUIRED" :{ section , info : 'OTP_CODE_FIELD_EMAIL_IS_REQUIRED' , msg : '' , code : 1003 } ,
  "OTP_TOKEN_FIELD_EMAIL_IS_REQUIRED" :{ section , info : 'OTP_TOKEN_FIELD_EMAIL_IS_REQUIRED' , msg : '' , code : 1003 } ,
  "OTP_CODE_FIELD_EMAIL_IS_EMPTY" :{ section , info : 'OTP_CODE_FIELD_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "OTP_TOKEN_FIELD_EMAIL_IS_EMPTY" :{ section , info : 'OTP_TOKEN_FIELD_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "SLUG_FIELD_TEMPLATE_EMAIL_IS_REQUIRED" :{ section , info : 'SLUG_FIELD_TEMPLATE_EMAIL_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "SLUG_FIELD_TEMPLATE_EMAIL_IS_EMPTY" :{ section , info : 'SLUG_FIELD_TEMPLATE_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "CONTENT_FIELD_TEMPLATE_EMAIL_IS_REQUIRED" :{ section , info : 'CONTENT_FIELD_TEMPLATE_EMAIL_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "CONTENT_FIELD_TEMPLATE_EMAIL_IS_EMPTY" :{ section , info : 'CONTENT_FIELD_TEMPLATE_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "TYPE_EMAIL_FIELD_TEMPLATE_EMAIL_IS_REQUIRED" :{ section , info : 'TYPE_EMAIL_FIELD_TEMPLATE_EMAIL_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "TYPE_EMAIL_FIELD_TEMPLATE_EMAIL_IS_EMPTY" :{ section , info : 'TYPE_EMAIL_FIELD_TEMPLATE_EMAIL_IS_EMPTY' , msg : '' , code : 1002 } ,
  "STATUS_FIELD_TEMPLATE_EMAIL_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_TEMPLATE_EMAIL_IS_REQUIRED' , msg : '' , code : 1002 } ,
  "TEMPLATE_EMAIL_NOT_FOUND" :{ section , info : 'TEMPLATE_EMAIL_NOT_FOUND' , msg : '' , code : 1001 } ,
  "EMAIL_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'EMAIL_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "SLUG_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'SLUG_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "SLUG_FIELD_PROVIDER_EMAIL_IS_EMPTY" :{ section , info : 'SLUG_FIELD_PROVIDER_EMAIL_IS_EMPTY' , msg : '', code : 1013 } ,
  "CLIENT_ID_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'CLIENT_ID_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "CLIENT_ID_FIELD_PROVIDER_EMAIL_IS_EMPTY" :{ section , info : 'CLIENT_ID_FIELD_PROVIDER_EMAIL_IS_EMPTY' , msg : '', code : 1013 } ,
  "CLIENT_SECRET_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'CLIENT_SECRET_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "CLIENT_SECRET_FIELD_PROVIDER_EMAIL_IS_EMPTY" :{ section , info : 'CLIENT_SECRET_FIELD_PROVIDER_EMAIL_IS_EMPTY' , msg : '', code : 1013 } ,
  "REFRESH_TOKEN_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'REFRESH_TOKEN_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "REFRESH_TOKEN_FIELD_PROVIDER_EMAIL_IS_EMPTY" :{ section , info : 'REFRESH_TOKEN_FIELD_PROVIDER_EMAIL_IS_EMPTY' , msg : '', code : 1013 } ,
  "MAX_SEND_DAY_TOKEN_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'MAX_SEND_DAY_TOKEN_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 } ,
  "STATUS_FIELD_PROVIDER_EMAIL_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_PROVIDER_EMAIL_IS_REQUIRED' , msg : '', code : 1013 }
}

