const section ='File'
export const  FileError   =  {
  "FILE_SECTION_NOT_FOUND" :{ section , info : 'FILE_SECTION_NOT_FOUND' , msg : '', code : 1000 } ,
  "FILE_STORAGE_NOT_FOUND" :{ section , info : 'FILE_STORAGE_NOT_FOUND' , msg : '', code : 1000 } ,
  "SECTION_FIELD_SECTION_IS_REQUIRED" :{ section , info : 'SECTION_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "SECTION_FIELD_SECTION_IS_EMPTY" :{ section , info : 'SECTION_FIELD_FILE_SECTION_IS_EMPTY' , msg : '' , code : 1001 } ,
  "PATTERN_TEMP_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG" :{ section , info : 'PATTERN_TEMP_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG' , msg : '', code : 1008 } ,
  "MINIMUM_CHARACHTERS_PREFIX_FIELD_FILE_SECTION_IS_3" :{ section , info : 'MINIMUM_CHARACHTERS_PREFIX_FIELD_FILE_SECTION_IS_3' , msg : '' , code : 1001 } ,
  "MAXIMUM_CHARACHTERS_PREFIX_FIELD_FILE_SECTION_IS_3" :{ section , info : 'MAXIMUM_CHARACHTERS_PREFIX_FIELD_FILE_SECTION_IS_3' , msg : '' , code : 1001 } ,
  "MIME_TYPES_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'MIME_TYPES_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "TYPE_CALC_THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'TYPE_CALC_THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "PATTERN_DESTINATION_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG" :{ section , info : 'PATTERN_DESTINATION_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG' , msg : '', code : 1008 } ,
  "MAX_SIZE_MIME_TYPE_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'MAX_SIZE_MIME_TYPE_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "WIDTH_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'WIDTH_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "HEIGHT_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'HEIGHT_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "MINIMUM_ITEMS_THUMBNAIL_FIELD_FILE_SECTION_IS_1" :{ section , info : 'MINIMUM_ITEMS_THUMBNAIL_FIELD_FILE_SECTION_IS_1' , msg : '' , code : 1001 } ,
  "MINIMUM_ITEMS_MIME_TYPES_FIELD_FILE_SECTION_IS_1" :{ section , info : 'MINIMUM_ITEMS_MIME_TYPES_FIELD_FILE_SECTION_IS_1' , msg : '' , code : 1001 } ,
  "STATUS_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "TYPE_SECTION_FILE_SECTION_IS_REQUIRED" :{ section , info : 'TYPE_SECTION_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "TTL_FILE_SECTION_IS_REQUIRED" :{ section , info : 'TTL_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "MAX_SIZE_UPLOAD_MIME_TYPE_IS_ABOVE_SELECTED" :{ section , info : 'MAX_SIZE_UPLOAD_MIME_TYPE_IS_ABOVE_SELECTED' , msg : '' , code : 1001 }



}

