const section ='File'
export const  FileError   =  {
  "FILE_SECTION_NOT_FOUND" :{ section , info : 'FILE_SECTION_NOT_FOUND' , msg : '', code : 1000 } ,
  "FILE_STORAGE_NOT_FOUND" :{ section , info : 'FILE_STORAGE_NOT_FOUND' , msg : '', code : 1000 } ,
  "SECTION_FIELD_SECTION_IS_REQUIRED" :{ section , info : 'SECTION_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "SECTION_FIELD_SECTION_IS_EMPTY" :{ section , info : 'SECTION_FIELD_FILE_SECTION_IS_EMPTY' , msg : '' , code : 1001 } ,
  "MIME_TYPES_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'MIME_TYPES_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "TYPE_CALC_THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'TYPE_CALC_THUMBNAIL_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "PATTERN_DESTINATION_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG" :{ section , info : 'PATTERN_DESTINATION_BUCKET_ID_IS_FIELD_FILE_SECTION_IS_WRONG' , msg : '', code : 1008 } ,
  "MAX_SIZE_MIME_TYPE_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'MAX_SIZE_MIME_TYPE_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "WIDTH_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'WIDTH_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "HEIGHT_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'HEIGHT_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "STATUS_FIELD_FILE_SECTION_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_FILE_SECTION_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "MAX_SIZE_UPLOAD_MIME_TYPE_IS_ABOVE_SELECTED" :{ section , info : 'MAX_SIZE_UPLOAD_MIME_TYPE_IS_ABOVE_SELECTED' , msg : '' , code : 1001 } ,
  "SLUG_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'SLUG_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 }  ,
  "SLUG_FIELD_ROLE_CDN_IS_EMPTY" :{ section , info : 'SLUG_FIELD_ROLE_CDN_IS_EMPTY' , msg : '' , code : 1001 }  ,
  "READ_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'READ_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 }  ,
  "TYPE_POLICY_AUTH_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'TYPE_POLICY_AUTH_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 }  ,
  "TYPE_POLICY_AUTH_FIELD_ROLE_CDN_IS_EMPTY" :{ section , info : 'TYPE_POLICY_AUTH_FIELD_ROLE_CDN_IS_EMPTY' , msg : '' , code : 1001 } ,
  "USER_OWNER_POLICY_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'USER_OWNER_POLICY_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "STATUS_POLICY_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'STATUS_POLICY_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "STATUS_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "WRITE_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'WRITE_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 }  ,
  "DELETE_FIELD_ROLE_CDN_IS_REQUIRED" :{ section , info : 'DELETE_FIELD_ROLE_CDN_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "PATTERN_APP_ACCESS_ID_IS_FIELD_ROLE_CDN_IS_WRONG" :{ section , info : 'PATTERN_APP_ACCESS_ID_IS_FIELD_ROLE_CDN_IS_WRONG' , msg : '', code : 1008 }

}

