const section ='MimeType'
export const  MimeTypeError   =  {
  "MIME_TYPE_NOT_FOUND" :{ section , info : 'MIME_TYPE_NOT_FOUND' ,msg : '', code : 1000 } ,
  "MIME_TYPE_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'MIME_TYPE_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "PATTERN_SOURCE_BUCKET_ID_IS_WRONG" :{ section , info : 'PATTERN_SOURCE_BUCKET_ID_IS_WRONG' , msg : '', code : 1013 } ,
  "PATTERN_DESTINATION_BUCKET_ID_IS_WRONG" :{ section , info : 'PATTERN_DESTINATION_BUCKET_ID_IS_WRONG' , msg : '', code : 1013 } ,
  "MINIMUM_LENGTH_PREFIX_FIELD_MIME_TYPES_IS_TWO" :{ section , info : 'MINIMUM_LENGTH_PREFIX_FIELD_MIME_TYPES_IS_TWO' , msg : '' , code : 1001 } ,
  "MAX_SIZE_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'MAX_SIZE_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "STATUS_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'STATUS_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "STATUS_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'STATUS_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "PATTERN_DESTINATION_ITEM_THUMBNAIL_BUCKET_ID_IS_WRONG" :{ section , info : 'PATTERN_DESTINATION_ITEM_THUMBNAIL_BUCKET_ID_IS_WRONG' , msg : '', code : 1013 } ,
  "MAX_SIZE_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'MAX_SIZE_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "WIDTH_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'WIDTH_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 } ,
  "HEIGHT_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED" :{ section , info : 'HEIGHT_ITEM_THUMBNAIL_FIELD_MIME_TYPES_IS_REQUIRED' , msg : '' , code : 1001 }





}

