name: tools-chain
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy :
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps :
      - name : checkout to repository
        uses : actions/checkout@v2
      - name : install and build
        run : npm ci
      - name : publish to registry
        uses : actions/setup-node@v2
        with :
          node-version : 21.6.2
          registry-url : "https://npm.pkg.github.com"
          scope : '@elyasbr'
      - run : npm publish
        env :
          NODE_AUTH_TOKEN : ${{secrets.GITHUB_TOKEN}}
